### ISSUE TITLE
Implement basic secret managment

### ISSUE THREAD

**Issue by lukasjarosch** [lukasjarosch/skipper#12]
Currently there is no way to handle secrets seamlessly.
Just as in kapitan, we want to be able to handle secrets transparently without the user having to actually see the secrets.

## Todo
- [x] Define and implement secret variable detection
- [x] Secrets should be represented by files, managed by certain drivers If the file is not existing, the secret is invalid
- [x] Basic driver handling implemented
- [x] Add the option to 'reveal' the secrets or not when rendering the data
- [x] Define and implement the secret creation process
- [x] Cleanup and refactor code which will be messy at this point
- [x] write example secret drivers 
- [x] Figure out how to configure secret drivers
